#!/usr/bin/env bash
# Update package lists
sudo apt update

# Install Nginx
sudo apt install -y nginx

# Configure Nginx
sudo tee /etc/nginx/sites-available/default > /dev/null <<EOF
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm;

    location / {
        return 200 "Hello World!";
    }
}
EOF

# Restart Nginx
sudo service nginx restart
