#!/usr/bin/env bash
# Update package lists
sudo apt update

# Install Nginx
sudo apt install -y nginx

# Configure Nginx
echo "Hello world" | sudo tee /var/www/html/index.html

# Restart Nginx
sudo service nginx restart
