#!/usr/bin/env bash
#script does the following


case "$1" in
    start)
        echo "Starting manage_my_process"
        /bin/bash /path/to/manage_my_process &
        echo $! > /var/run/my_process.pid
        ;;
    stop)
        echo "Stopping manage_my_process"
        kill $(cat /var/run/my_process.pid)
        rm /var/run/my_process.pid
        ;;
    restart)
        echo "Restarting manage_my_process"
        kill $(cat /var/run/my_process.pid)
        rm /var/run/my_process.pid
        /bin/bash /path/to/manage_my_process &
        echo $! > /var/run/my_process.pid
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac
