#!/usr/bin/env bash
# This script displays the PID and process name of processes whose name contains the word "bash".

for pid in /proc/*/status ; do
    if grep -q "bash" $pid ; then
        echo "$(awk '/Pid|Name/{printf("%s ", $2)}' $pid)"
    fi
done
