#!/usr/bin/env bash
#Script to kill a process in another terminal.

# Find the PID of the 4-to_infinity_and_beyond process
pid=$(ps -ef | grep "4-to_infinity_and_beyond" | grep -v grep | awk '{print $2}')

if [ -n "$pid" ]; then
  # If the process is running, terminate it
  kill $pid
  echo "Terminated"
else
  echo "Process 4-to_infinity_and_beyond is not running"
fi
