#!/usr/bin/env bash
#script to terminate a process without using kill or killall.
# Find the PID of the 4-to_infinity_and_beyond process

PID=$(pgrep 4-to_infinity_and_beyond)

# Terminate the process
if [ -n "$PID" ]; then
  kill -SIGTERM "$PID"
else
fi
