#!/usr/bin/env bash
#This script displays "To infinity and beyond" indefinitely, with a 2-second sleep in between each iteration, and displays "I am invincible!!!"

trap 'echo "I am invincible!!!"; exit' SIGTERM

while true; do
echo "To infinity and beyond"
sleep 2
done
