#!/usr/bin/env bash
# This script displays the username, user id, and home directory path for each user in /etc/passwd.
# Read the file line by line with a while loop and display the relevant information for each line

while IFS=: read -r username _ uid _ _ home _; do
    echo "Username: $username"
    echo "User ID: $uid"
    echo "Home Directory: $home"
done < /etc/passwd
