#!/usr/bin/env bash
# script  displays "bad luck" for the 4th loop iteration, "good luck" for the 8th loop iteration, and "Best School" for the rest from 1 to 10.

for i in {1..10}
do
    if [ $i -eq 4 ]
    then
        echo "bad luck"
    elif [ $i -eq 8 ]
    then
        echo "good luck"
    else
        echo "Best School"
    fi
done
